name: Publish Docker image

on:
  push:
    branches: [ "main" ]
  release:
    types: [published]
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4.2.2

      - name: 登录到 Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v3.2.0

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: 构建并推送 Docker 镜像
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sing-box-subscribe:latest
